export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const CHANGE_TODO_COLOR = "CHANGE_TODO_COLOR";

export const SET_COLOR_FILTERS = "SET_COLOR_FILTERS";
export const SET_STATUS_FILTERS = "SET_STATUS_FILTERS";
